/**
 * modelCatalog 烟测（不依赖 SQLite）
 * 运行：node scripts/model-catalog.test.cjs
 */
const assert = require('assert')
const { inferModality, inferVendor, normalizeVendor, inferSupportsReferenceVideo, inferApiProfile, isStoreModalityUnset } = require('../services/modelCatalogService')
const { catalogDisplayName } = require('../services/catalogDisplayName')

assert.strictEqual(inferModality('doubao-seedance-2-0-260128'), 'video')
assert.strictEqual(inferModality('doubao-seedream-5.0-lite'), 'image')
assert.strictEqual(inferModality('doubao-seed-1-6-250615'), 'text')
assert.strictEqual(inferModality('gpt-5-mini'), 'text')
assert.strictEqual(isStoreModalityUnset('unknown'), false)
assert.strictEqual(isStoreModalityUnset('text'), false)
assert.strictEqual(isStoreModalityUnset(''), true)
assert.strictEqual(isStoreModalityUnset(null), true)
assert.strictEqual(inferVendor('doubao-seedance-2-0-260128'), '豆包')
assert.strictEqual(normalizeVendor('openai', ''), 'OpenAI')
assert.strictEqual(normalizeVendor('MiniMax', ''), 'MiniMax')
assert.strictEqual(normalizeVendor('minimax', 'custom-model'), 'MiniMax')
assert.strictEqual(inferVendor('happyhorse-1.0-i2v'), '阿里云')
assert.strictEqual(normalizeVendor('custom', 'happyhorse-1.0-i2v'), '阿里云')
assert.strictEqual(inferModality('happyhorse-1.0-t2v'), 'video')
assert.strictEqual(inferModality('happyhorse-get'), 'video')
assert.strictEqual(inferVendor('grok-3'), 'xAI')
assert.strictEqual(inferVendor('grok-4.1-fast-non-reasoning'), 'xAI')
assert.strictEqual(normalizeVendor('custom', 'grok-3-deepsearch'), 'xAI')
assert.strictEqual(inferSupportsReferenceVideo('doubao-seedance-2-0-260128'), true)
assert.strictEqual(inferSupportsReferenceVideo('doubao-seedance-2.0-fast-260128'), true)
assert.strictEqual(inferSupportsReferenceVideo('seedance-2-0-get'), false)
assert.strictEqual(inferSupportsReferenceVideo('doubao-seedance-1-5-pro'), false)
assert.strictEqual(inferSupportsReferenceVideo('kling-v3'), false)
assert.strictEqual(inferSupportsReferenceVideo('kling-v2-6'), true)
assert.strictEqual(inferSupportsReferenceVideo('kling-v2-5'), true)
assert.strictEqual(inferSupportsReferenceVideo('kling-v2-6-image2video'), false)
assert.strictEqual(inferSupportsReferenceVideo('kling-v3-get-all'), false)
assert.strictEqual(inferSupportsReferenceVideo('kling-image2video-get'), false)
assert.strictEqual(inferSupportsReferenceVideo('kling-v3-video-generation'), false)
assert.strictEqual(inferSupportsReferenceVideo('kling-v1-video-generation'), false)
assert.strictEqual(inferSupportsReferenceVideo('wan2.6-r2v'), true)
assert.strictEqual(inferSupportsReferenceVideo('happyhorse-1.0-r2v'), false)
assert.strictEqual(inferApiProfile('happyhorse-1.0-r2v'), 'happyhorse-r2v')
assert.strictEqual(inferApiProfile('viduq3-pro'), 'vidu-t2v')
assert.strictEqual(inferSupportsReferenceVideo('unknown-model', '支持参考视频生成'), false)

const { mergeRemoteMeta, formatDmxapiPriceText, buildDmxapiPriceDisplay } = require('../services/dmxapiModelMeta')
const klingMeta = mergeRemoteMeta('kling-v3-video-generation', 'video', null, 1)
assert.ok(klingMeta.tags.includes('视频'))
assert.ok(klingMeta.remark.includes('文生'))
assert.ok(!/参考视频及|支持参考视频/.test(klingMeta.remark))
assert.strictEqual(klingMeta.dmxapiPrice.kind, 'empty')
const klingToken = mergeRemoteMeta('kling-v3-video-generation', 'video', { price_info: { default: { default: { model_ratio: 0.5, model_completion_ratio: 100 } } } }, 1)
assert.strictEqual(klingToken.dmxapiPrice.kind, 'token')
const tableDisplay = buildDmxapiPriceDisplay(
  { price_info: { default: { default: { priceInfo: [['不含视频输入', '480p', '0.371'], ['含视频输入', '720p', '0.563']] } } } },
  1,
)
assert.strictEqual(tableDisplay.kind, 'table')
assert.ok(tableDisplay.rows.length === 2)
assert.strictEqual(formatDmxapiPriceText({ price_info: { default: { default: { quota_type: 0, model_price: 0 } } } }), '免费')
const tokenDisplay = buildDmxapiPriceDisplay({ price_info: { default: { default: { model_ratio: 470.588, model_completion_ratio: 1 } } } }, 1)
assert.strictEqual(tokenDisplay.kind, 'token')
assert.ok(tokenDisplay.lines.some((l) => l.includes('941.18')))
assert.strictEqual(catalogDisplayName('kling-v3-get'), 'kling-v3-get')
assert.strictEqual(catalogDisplayName('wan2.6-t2v', 'Wan 视频'), 'wan2.6-t2v')

console.log('[model-catalog.test] OK')
